name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build
        run: |
          msbuild d3d8to9.sln /p:Configuration=Release /p:Platform=x86

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: d3d8.dll
          path: './bin/Release/d3d8.dll'
